### ISSUE TITLE
Nouveaux paragraphes absents dans B 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#11]
Et voici le souci lié aux paragraphes absents dans le ms. B : 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/ee532cccbd166649754976257a88fd871e9871de/TEI/Collation_essai.xml#L324
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/ee532cccbd166649754976257a88fd871e9871de/TEI/Collation_essai.xml#L611

**Comment by Camille-Carnaille** [comment]
Solution proposée par Bertrand Gaiffe et appliquée : 

p><anchor xml:id="idPara"/>le contenu du paragraphe<app from="#ipPara"><rdg wit=#B"/></app</p>

**Comment by Camille-Carnaille** [comment]
Nouvelle réflexion à la révision en mode HTML du document de Collation_essai : 
Il me semble que la solution envisagée donne l'impression que le contenu entier du paragraphe soit manquant. 
Je suggère donc, selon une proposition faite et revue avec Bertrand Gaiffe : 
```xml<lem wit="#V"><c ana="lettrine2">Q</c></lem><rdg wit="#B">Q</rdg> ```
Ce n'est pas exactement la même idée d'un nouveau paragraphe, mais, en soi, la lettrine en est la meilleure trace...

**Comment by gabays** [comment]
C'est à vous de voir. tu peux mettre `@source` pour pointer vers le ms

**Comment by Camille-Carnaille** [comment]
Merci @gabays pour la prompte réponse, comme ça je suis sûre de la solution théorique pour la discuter en équipe :)

**Comment by Camille-Carnaille** [comment]
Pas la peine d'indiquer la source avec attribut pour le rendu en apparat 
"Pas de nouveau § B" OU à l'inverse "Nouveau § B"
