### ISSUE TITLE
Interventions narratoriales

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#17]
Question de balisage des interventions narratoriales, suite à un très juste échange avec @SophieLecomte : 
Ne serait-il pas préférable de baliser la formule "Ci dit li contes" en plus/à la place de ce qui suit ? 
à discuter !

**Comment by PrunelleDeleville** [comment]
Oui !

**Comment by Camille-Carnaille** [comment]
Accord en équipe de baliser sous cette forme > à modifier chez Brodtkorb et dans nos parties déjà balisées !
