### ISSUE TITLE
Noms de peuples

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#18]
Suivant la question très juste aussi de @SophieLecomte, il serait bon de savoir comment baliser les noms de peuples (si tant est que @Simone Ventura trouve cela souhaitable), je n'ai pas trouvé la balise adéquate : une idée, @gabays ?

**Comment by gabays** [comment]
pourquoi pas 
```xml
le <name type="people">Frison</name> et le <rs type="person">duc de <placeName>Lucembourc</placeName></rs>
```

**Comment by SophieLecomte** [comment]
J'ai donc balisé ainsi jusqu'à présent. Par contre, j'intègrerais uniquement les peuples (les Bretons, les Frisons, etc.) et non les mentions Machin le Frison. Qu'en pensez-vous?

**Comment by SophieLecomte** [comment]
<name type="people" key="Grecs/Frisons/Bretons">

**Comment by SophieLecomte** [comment]
avec une key ="Frisons" etc.

**Comment by Camille-Carnaille** [comment]
Reposer la question à Simone !

**Comment by simoneve74** [comment]
OK pour les noms de peuples. La proposition de balisage me semble claire/efficace.

**Comment by Camille-Carnaille** [comment]
Merci, @simoneve74  ! 
La règle a été créée dans l'ODD !
Il ne faudra pas oublier de veiller à ces ajouts dans la partie Brodtkorb : je me charge des remplacements automatiques que j'ai en tête et si tu veux y regarder à la relecture, @PrunelleDeleville, ce serait parfait :)
