### ISSUE TITLE
Lignes effacées en début de V3 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#19]
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/12f6f4fe90ea703161bde2204f7bc5177d2724a7/TEI/%C2%A7483-851_Camille.xml#L228
Quid du balisage de cette info ?
A fortiori, je repose la question des lignes effacées, n'est-ce pas plutôt les lignes du verso qui sont visibles, c'est ce qu'il me semble, même si on est d'accord qu'il est étrange que rien ne soit écrit d'emblée.
cf. https://gallica.bnf.fr/ark:/12148/btv1b52513332z/f7.item.r=fran%C3%A7ais%2022550.zoom

**Comment by PrunelleDeleville** [comment]
Au début du texte, après la grosse lettrine, il y a clairement des lignes effacées (ce qui n'est pas étonnant sur le premier feuillet du manuscrit).
Il me semble que cette info devra faire partie de l'apparat, car là il va falloir corriger. Mais il me semble qu'il existe une balise pour dire que le manuscrit est endommagé ici : unclear reason = effacé?

**Comment by Camille-Carnaille** [comment]
Pardon, je n'étais pas claire, je parlais de la rubrique !
Pour les premières lignes du paragraphe après la rubrique, on n'a par contre pas indiqué de balise unclear, cela vous paraît nécessaire ?
