### ISSUE TITLE
Collation - om.

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#2]
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/08511187a842c2d808b35a8d34491d5bf11b6017/TEI/Collation.xml#L223

Puis-je collationner une variante comme manquante sous la forme "om." ?
Est-il préférable dans ce cas de l'indiquer en italique ? (soyons maniaques)

**Comment by gabays** [comment]
Déjà: pourquoi c'est dans un autre document?

**Comment by Camille-Carnaille** [comment]
Hein ?

**Comment by Camille-Carnaille** [comment]
En effet, help wanted me paraît bien ahah

**Comment by gabays** [comment]
Il faut laisser la balise vide. Cf. [les guidelines](https://tei-c.org/release/doc/tei-p5-doc/en/html/TC.html).
