### ISSUE TITLE
Balisage des informations de mise en page 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#20]
Au-delà de la question des lignes effacées, se pose de manière plus large la question du balisage des informations de mise en page, du type comme ici : 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/12f6f4fe90ea703161bde2204f7bc5177d2724a7/TEI/%C2%A7483-851_Camille.xml#L540
Une préférence ? 
@gabays, une recommandation particulière ou nos choix seront les bons ? :)

**Comment by Camille-Carnaille** [comment]
Peut-être pas une info cruciale en fait, a fortiori parce qu'on ne va pas l'indiquer pour les autres mss. collationnés et parce que, surtout, on n'a pas noté chacune des lignes. à discuter en équipe !

**Comment by gabays** [comment]
Vu qu'on ne le met pas dans une édition, pourquoi le mettre dans la TEI?

**Comment by Camille-Carnaille** [comment]
Cf. autre issue : proposition de balisage comme ajout si on décide de le garder ? 

cf. ce cas-ci aussi : 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/083c73ebb4adf7c51d726c895732904303baa892/TEI/%C2%A7483-851_Camille.xml#L875-876

**Comment by Camille-Carnaille** [comment]
C'est en fait par souci de cohérence avec les autres notes que l'on a prises sur des info interlinéaires etc. que je pose la question, mais la question est juste ouverte, je ne sais pas en effet quel serait notre but exact, d'où l'issue ouverte :)

**Comment by Camille-Carnaille** [comment]
Quid de ça, aussi ? 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/09dd99425600a9d2b2b49881af012f6b0f97749f/TEI/%C2%A7483-851_Camille.xml#L1506

**Comment by gabays** [comment]
Tu peux mettre un `<glyph>`? https://tei-c.org/release//doc/tei-p5-doc/en/html/ref-glyph.html

**Comment by Camille-Carnaille** [comment]
Merci encore, @gabays <3

**Comment by Camille-Carnaille** [comment]
Tout (croix, lignes supplémentaires, etc.) à noter en codico > cf. @SophieLecomte 
Garder cette issue pour les autres cas plus particuliers à indiquer à Sophie !
