### ISSUE TITLE
Souci xpr - au secours !

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#21]
@gabays, oxygen m'a indiqué un bug, que j'ai cru bon de régler comme il le recommandait. Sauf que depuis, j'ai plein d'xpr, c'est bizarre. Tout fonctionne maintenant que j'ai regéré le bon fonctionnement des scripts dans nos fichiers, mais ça ne me convient pas des masses qu'il y existe plusieurs xpr (le _normal_, et un dans le dossier TEI) et ça ne me semble pas être une bonne idée à terme.
C'est d'autant plus étrange que cet autre fichier xpr n'existe pas sur ma machine...
On regarde à ça demain aussi ?

**Comment by gabays** [comment]
Solved. N'oubliez pas de pouler. 🐓
