### ISSUE TITLE
Balisage des `<rs>`

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#23]
Pour s'assurer de la continuité de nos choix de balisage, je me demandais si nous préférions encoder l'article défini dans la balise `<rs>`ou plutôt pas ?

**Comment by PrunelleDeleville** [comment]
Perso, je ne pense pas qu'il faille intégrer l'article

**Comment by SophieLecomte** [comment]
Je pense que ce sera moins couteux d'intégrer l'article, comme vous l'avez déjà fait pour la parie Brodtkorb. Il faut décider ce que l'on fait pour les prépositions articulées "au", "du", etc.

**Comment by Camille-Carnaille** [comment]
On intègre toujours l'article défini et possessif (pas les indéfinis, ni "au", "du", etc.)
