### ISSUE TITLE
Balisage des lettres en paroles rapportées

### ISSUE THREAD

**Issue by PrunelleDeleville** [CycleDes7Sages/CycleDes7Sages.github.io#25]
@Camille-Carnaille  @SophieLecomte 
peut-on préciser d'une façon ou d'une autre que la parole rapportée est une lettre? Ou cela n'est peut-être pas intéressant?

**Comment by Camille-Carnaille** [comment]
Davantage qu'en parole rapportée, il y a le cas où le contenu de la lettre pourrait être balisé au discours direct. On balise ainsi alors ?
Voir : https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/ba86446a9986a6e37f8e5ae3f7862ba5dce7a9c9/TEI/%C2%A7483-851_Camille.xml#L1959-L1960

**Comment by PrunelleDeleville** [comment]
d'ac pour discours direct

**Comment by Camille-Carnaille** [comment]
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/a13a249f48fd3d8293bcee27f981f71e48651e3a/TEI/%C2%A7135-188_Prunelle.xml#L58-L60

**Comment by Camille-Carnaille** [comment]
OK discours direct 
Si contenu de la lettre inscrit dans un discours, alors discours enchâssé
