### ISSUE TITLE
Changement de main au f.3 de V3 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#28]
Comment balise-t-on le changement de main au f.3 de V3 ?
`<note type="apparat">` ou autre chose ?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/083c73ebb4adf7c51d726c895732904303baa892/TEI/%C2%A7483-851_Camille.xml#L877

**Comment by gabays** [comment]
[<handShift>](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-handShift.html) ?

**Comment by Camille-Carnaille** [comment]
Merci beaucoup @gabays pour la prompte réponse ! C'est pile ça qu'il me fallait, et mes recherches, dans mes notes de nos cours/discussions, et dans les guidelines, n'avaient pas été productives ! 
Problem solved et guide de balisage pour le projet mis à jour et posté sur le cloud :)
