### ISSUE TITLE
Code non valide

### ISSUE THREAD

**Issue by gabays** [CycleDes7Sages/CycleDes7Sages.github.io#3]
@Camille-Carnaille la balise `<said>`n'est pas fermée ici

https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/08511187a842c2d808b35a8d34491d5bf11b6017/TEI/Collation.xml#L365

**Comment by Camille-Carnaille** [comment]
Je saiiiis, j'y venais didjou !

Puisque tu soulèves toi-même mon souci : comment puis-je baliser ma variante qui inclut la balise _said_, mais qui en déborde aussi ?

**Comment by gabays** [comment]
Il y a un problème avec la balise `<said>`. Il faut utiliser la [Double End-Point Attachment Method](https://tei-c.org/release/doc/tei-p5-doc/en/html/TC.html#TCAPDE). En gros, plutôt que d'avoir ça:
```xml
<p>
   Ici je vais avoir une 
   <app>
      <lem><said>variante</lem>
      <rdg>variant</rdg>
   </app>
   </said>
</p>
```
tu vas utiliser ça:
```xml
<p>
   <said>
      Ici je vais avoir une <anchor xml:id="debutVariante"/> <said>variante
         <app from="#debutVariante">
            <rdg>variant</rdg>
         </app>
      </said>
</p>
```
Seule la variante est encodée, la leçon retenue reste dans le corps du texte. Le début de la variation se trouve encodé avec une balise `<anchor>` et son `@xml:id`.

Une manière de gérer les `@xml:id` et de recommencer la numérotation à chaque paragraphe: `@xml:id="P1L1"` pour la première variante du premier paragraphe
```xml
<p xml:id="P1">
   <said>
      Ici je vais avoir une <anchor xml:id="P1V1"/> <said>variante
         <app from="#P1V1">
            <rdg>variant</rdg>
         </app>
      </said>
</p>
```

Le résultat donnerait donc:
```xml
<p xml:id="P1">
   <anchor xml:id="identifiantUnique1"/>Il
   <app from="dentifiantUnique1">
      <rdg wit="#G">Ilz</rdg>
   </app> 
   <anchor xml:id="identifiantUnique2"/>distrent que <said aloud="true" direct="false">
      <num>ii</num> mauvaises <anchor xml:id="identifiantUnique3"/>fames
      <app from="#identifiantUnique3">
         <rdg wit="#G">femmes</rdg>
      </app> 
      estoient
      <app from="#identifiantUnique2">
         <rdg wit="#B"/>
      </app> 
      qui moult avoient <anchor xml:id="identifiantUnique4"/>fait de maus
      <app  from="#identifiantUnique4">
         <rdg wit="#B">de maus fait</rdg>
      </app>
   </said>. 
</p>
```

**Comment by Camille-Carnaille** [comment]
Je réouvre la question parce que je réalise que cette solution, pratique à plein de niveaux, on est d'accord, ne me permet pas, de ce que j'en comprends à ce stade, d'informer les changements de manuscrit de base dans les variantes retenues 
(il va forcément se présenter des cas où l'on va s'écarter de la leçon de V2/V3 fautive et préférer B par exemple, il faudrait donc quand même pouvoir indiquer d'où on tire anchor, même si ce n'est que de manière exceptionnelle ailleurs que dans V, non ?)

**Comment by Camille-Carnaille** [comment]
Bertrand me dit qu'il n'est pas possible de préciser la source de la leçon retenue dans la balise anchor... :( 
Du coup, il me propose plutôt de scinder les balises said, je n'ai pas encore réussi à l'intégrer dans mon odd (apparemment c'est plus compliqué que ça), mais je te donne toujours ici sa solution : 
<said next="#n1">bla bla</said>...<said xml:id="n1" next="#n2">bli bli</said>...<said xml:id="n2">blu blu</said>

Subsiste le souci des nouveaux paragraphes, je le lui ai posé la question aussi dans ce cas de figure.

**Comment by Camille-Carnaille** [comment]
Cf. autre issue maintenant fermée, une solution a été proposée et appliquée avec succès (bon, pas que par moi, maiiiiis ça compte :))
Voilà le code valide !
