### ISSUE TITLE
Liens de parenté en présence d'un nom propre

### ISSUE THREAD

**Issue by SophieLecomte** [CycleDes7Sages/CycleDes7Sages.github.io#30]
Balise-t-on "son frere", "sa suer", etc. dans les cas d'apposition avec un nom propre?
Ex. Helcanus, son frere OU son frere Helcanus
Idem pour "l'empereur Cassidorus" -> balise-t-on seulement Cassidorus?

**Comment by Camille-Carnaille** [comment]
Quand le nom propre est donné juste avant/après, on se contente de la balise `<persName>` :)

**Comment by PrunelleDeleville** [comment]
Pour les cas de "suer", "frere", je ne baliserais pas. Ex pour  Helcanus, son frere OU son frere Helcanus, balise que sur Helcanus
Idem pour "Cassidorus" l'empereur, balise que sur Cassidorus
