### ISSUE TITLE
balise unclear quand il n'y a rien dedans

### ISSUE THREAD

**Issue by PrunelleDeleville** [CycleDes7Sages/CycleDes7Sages.github.io#31]
Ex d'une balise unclear sans dire dedans car on ne peut pas lire le texte.
On fait ainsi?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/baea02d3e7f1d4236a2567fed53778f4a554e2fa/TEI/%C2%A7135-188_Prunelle.xml#L670

**Comment by Camille-Carnaille** [comment]
On met trois petits points dans ces cas-là entre les deux balises !
