### ISSUE TITLE
Keys 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#32]
J'ouvre une issue au sujet des keys pour référer nos noms de lieux et de personnages, tout en faisant le lien avec notre GoogleDrive : 
https://docs.google.com/document/d/15YEaew78JYT5Sbn5WP_MSNIyGSxefJLs/edit

Je me pose notamment la question du titre de Bourleus : 
Lembourc = Limbourg ?

Et pour le duc de Nise, c'est la Nicée ? On est d'accord que c'est de Karus dont il est question ?

**Comment by SophieLecomte** [comment]
Pour le moment, j'ai balisé "duc de Nise" ou "??" par facilité pour moi (et n'ayant pas encore compris à quoi réfère "Nise"). Ne ferait-on pas le point quand on a fini de baliser? C'est peut-être un peu chronophage de revoir certaines balises sur l'ensemble de nos documents, mais ça permettrait sans doute d'unifier de manière plus certaine.
Pour Lembourc, j'ai mis Limbourg, en sachant que c'est peut-être erroné, et que de nouveau ça peut facilement s'unifier sur la fin ("Limbourg" n'apparaissant jamais, je pense, dans le roman en lui même, cela facilite le remplacement automatique).

**Comment by Camille-Carnaille** [comment]
Autre question de ce côté : 
Palais Majeur en placeName ou en rs ?

**Comment by Camille-Carnaille** [comment]
Deux questions que je me pose en terme de nécessiter de baliser : 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7483-851_Camille.xml#L2909

**Comment by PrunelleDeleville** [comment]
@Camille-Carnaille @SophieLecomte @PrunelleDeleville 
Pour "autel saint Michiel", je baliserai en place Name et saint Nicholas en persName.
Palais Majeur en placeName
Pour Limbourg, on est d'accord que la glose sera "Limbourg", mais la key doit être la version du texte, donc plutôt un truc comme "Lembourc". Mais sur ce point, le plus important si nous n'avons pas fait pareil et de bien garder trace dans le Google drive.
Idem pour "Nise", si c'est la "Nicée" c'est dans la glose, pas dans la key, me semble-t-il. "Nicée" me paraît être une bonne glose.

**Comment by Camille-Carnaille** [comment]
Ta très juste réflexion me fait repenser à ce qu'on veut rendre par la glose : on a indiqué Rome, et non Romme, Constantinople et non une autre orthographe plus médiévale. Il faut réfléchir plus largement à ce que l'on souhaite faire rendre, non ? 
Pour les noms de lieux en particulier, ne serait-ce pas préférable d'indiquer la graphie attendue aujourd'hui pour faciliter l'identification du lieu puis de lister les orthographes (la majoritaire en première) ?
C'est une vraie question, pour rebondir sur les nôtres d'hier matin...

**Comment by PrunelleDeleville** [comment]
Très juste, pour les noms de lieux ce serait intéressant d'uniformiser selon l'usage moderne. En tout cas, inconsciemment, c'est ce qu'on semble avoir fait

**Comment by SophieLecomte** [comment]
Pour rebondir sur la discussion de lundi: pour éviter de revoir ce qu'on a déjà fait et risquer de ne pas être uniformes dans nos propres fichiers, je pense qu'il faut continuer comme on a fait, en étant bien conscientes (ce qui m'avait personnellement échappé) que la key doit référer à la graphie attestée dans le texte (majoritaire ou pas, on verra en équipe ce qu'on veut faire). Tout sera à revoir, en somme, mais autant être cohérentes au sein d'un même fichier pour faciliter les remplacements après-coup.

**Comment by SophieLecomte** [comment]
Pour Palais Majour, il faut être sûres qu'il s'agit bien d'un lieu-dit: on se posait déjà la question avec Prunelle de savoir s'il fallait ou non des majuscules. Je poserais la question en équipe.
Pour "autel" et "chapelle" saint Nicholas, comme il ne s'agit pas du génitif "de saint Nicholas" ici, voir aussi si on fait comme en français moderne, où "Saint" prend une majuscule pour les lieux de culte et pour les fêtes. À voir.

**Comment by Camille-Carnaille** [comment]
Je pense vraiment qu'il faudrait en effet qu'on prenne la peine de discuter du rendu souhaité, mais aussi de l'utilité en terme d'identification numérique et pas seulement dans le résultat papier d'ailleurs (ne pas oublier en somme que si on s'amuse à baliser, c'est aussi pour ça :)), en équipe. 
Il y a une question de rendu, mais aussi de cohérence en terme de rendu des infos justement (rs au nom que l'on a nous donné et donc exprimé forcément sous une forme modernisée, nom de lieu type Rome qu'on a rendu comme Rome et non Romme (forme forcément majoritaire dans le manuscrit)). 
Plus spécifiquement, je me demandais en effet pour Palais Majeur en raison des majuscules justement. 
Quant à autel Nicolas, j'aurais tendance à baliser ce lieu parce que c'est donc l'église à l'édification de laquelle contribue Cassidorus, elle est donc très souvent nommée, mais c'est juste mon idée. Préfère-t-on en rs ou en placeName c'est encore une autre question. Je préfère dans tous les cas faire de l'extensif dans nos choix de balisage à ce stade, mais je pense vraiment qu'il serait bon qu'on se décide à avoir une vraie discussion sur ce qu'on attend de tout ça assez vite

**Comment by SophieLecomte** [comment]
"Autel" et "Chapelle" à baliser évidemment. Et en placeName selon moi. La question des majuscules reste pour moi ouverte dans ces cas particuliers.

**Comment by Camille-Carnaille** [comment]
D'accord, sur ça, je vous suis bien sûr, mais ainsi on se met d'accord sur cette part du balisage :)

**Comment by Camille-Carnaille** [comment]
Idem que pour l'_issue_ "Qui est qui ?", je propose une réunion au sujet de nos keys et flous persistants dans l'identification des lieux et personnages
