### ISSUE TITLE
Chansons

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#34]
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7483-851_Camille.xml#L2835
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7483-851_Camille.xml#L2843

**Comment by PrunelleDeleville** [comment]
Pour moi ce sont des proverbes, en tout cas des tournures proverbiales. Même s'ils ne figurent pas chez Morawski ou Di Stefano, il me semble utile de les relever.

**Comment by SophieLecomte** [comment]
Je les relèverais aussi comme "proverbes" pour l'instant, tout en sachant qu'on devra sans doute faire une distinction dans notre liste future entre "proverbes", "tours proverbiaux" (non renseignés dans les ouvrages de référence) et "expressions sentencieuses", comme cela se fait parfois.

**Comment by Camille-Carnaille** [comment]
Le truc, c'est qu'ils sont dits chanter, et la mise en forme du texte sur le manuscrit en est explicite, ça dépasse le proverbe (même si on peut aussi indiquer qu'ils chantent qqch qui se rapproche d'un proverbe hein, mais ma question était plus de l'ordre de la prise en compte de la chanson, de l'insertion lyrique donc et de sa mise en forme manuscrite).

**Comment by SophieLecomte** [comment]
Je suis passée à côté de la question. C'est donc un cas particulier, qui n'est pas un proverbe. Je n'ai pas de réponse.

**Comment by Camille-Carnaille** [comment]
J'ai indiqué en proverbe, tout en restant convaincue du cas limite que ces deux chansons constituent à ce typage du balisage.
