### ISSUE TITLE
Proverbes 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#35]
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7483-851_Camille.xml#L2921

**Comment by Camille-Carnaille** [comment]
Oups, le deuxième exemple n'est pas indiqué en entier, je recommence : 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7483-851_Camille.xml#L2958-2959

**Comment by PrunelleDeleville** [comment]
Dans ce cas, en effet, c'est proverbial
