### ISSUE TITLE
Texte après l'enluminure

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#36]
Est-il souhaitable/possible de baliser cela ?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7483-851_Camille.xml#L3119

**Comment by PrunelleDeleville** [comment]
@Camille-Carnaille pardon, je ne comprends pas la question.

**Comment by Camille-Carnaille** [comment]
Le texte ne commence pas ici au début du folio, mais après l'enluminure (une section de texte étant bien souvent indiquée aussi avant l'enluminure et donc selon une répartition en deux temps du texte sur la colonne), je me demande s'il faut baliser cette information de manière spécifique et si oui comment

**Comment by SophieLecomte** [comment]
D'accord avec Prunelle.
