### ISSUE TITLE
Noms de peuple, lesquels ?

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#37]
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7483-851_Camille.xml#L3212

**Comment by PrunelleDeleville** [comment]
@Camille-Carnaille @SophieLecomte @simoneve74 
"lorain" est ici un nom commun

**Comment by SophieLecomte** [comment]
Je n'ai pour l'instant balisé les noms de peuples que quand ils réfèrent aux peuples (les Grecs, les Frisons, etc.), et non "un Grec" ou "un Lorrain" en particulier.

**Comment by Camille-Carnaille** [comment]
Ok, faisons ainsi !
