### ISSUE TITLE
Qui est qui?

### ISSUE THREAD

**Issue by PrunelleDeleville** [CycleDes7Sages/CycleDes7Sages.github.io#38]
@Camille-Carnaille @SophieLecomte @simoneve74 
Voici une liste de passage où je ne sais pas identifier la key de la "rs"

1. https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7135-188_Prunelle.xml#L668

même personne:
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7135-188_Prunelle.xml#L675

2- pour la mention d'un château, vous précisez le nom du château en "rs"?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7135-188_Prunelle.xml#L273
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7135-188_Prunelle.xml#L938

3. pour le duc d'Athènes, le fils ou le père?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7135-188_Prunelle.xml#L415

4. il est question d'un hôte, je crée une "key" "hôte deXXX"?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7135-188_Prunelle.xml#L436

5. on balise les messagers?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7135-188_Prunelle.xml#L865

**Comment by SophieLecomte** [comment]
Je devrais relire une plus grande portion de texte aussi, sorry je ne sais pas t'aider comme ça.

**Comment by PrunelleDeleville** [comment]
Hum, je dirais place Name. Ici ce n'est pas le saint qui est important mais le nom du lieu seulement, à mon avis.

**Comment by SophieLecomte** [comment]
Dans le cas de la chapelle, je mettrais aussi "placeName". Je vous contacte sur WA avec des propositions de dates pour la réunion "rs" et co.

**Comment by Camille-Carnaille** [comment]
@PrunelleDeleville, a-t-on pu résoudre toutes tes questions ? En te relisant, il me semble avoir précisé à chaque fois, mais peut-être y a-t-il encore des soucis, auquel cas n'hésite pas (et pardon de ne pas avoir répondu à cela mieux plus tôt !)

**Comment by PrunelleDeleville** [comment]
Tout bon pour moi
