### ISSUE TITLE
Balisage problèmes lecture ms référence

### ISSUE THREAD

**Issue by PrunelleDeleville** [CycleDes7Sages/CycleDes7Sages.github.io#39]
Coucou! c'est de nouveau moi!
@Camille-Carnaille @SophieLecomte 

une fois, nous avons mis que nous avions du mal à lire à cause d'un souci de transparence. Est-ce que je mets plutôt l'attribut "faded"?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/321a41480d86ef76a3f1d3fd712dd89228a719cf/TEI/%C2%A7135-188_Prunelle.xml#L1282

**Comment by Camille-Carnaille** [comment]
Oui

**Comment by Camille-Carnaille** [comment]
Enfin, ou on crée une nouvelle raison même si je ne connais pas d'occurrence de ce type dans les guidelines

**Comment by SophieLecomte** [comment]
Je m'en remets à ce que propose Camille.

**Comment by Camille-Carnaille** [comment]
La question est donc considère-t-on que le texte est un peu délavé, comme _faded_ le laisse entendre, ou souhaite-t-on vraiment évoquer un souci de transparence, qui peut d'ailleurs être seulement propre à la numérisation (je ne sais pas hein) ?

**Comment by PrunelleDeleville** [comment]
il ne me semble pas utile d'évoquer un souci lié à la transparence si ceci vient de la numérisation et qu'avec le manuscrit dans les mains on n'a pas de difficultés à lire.

**Comment by Camille-Carnaille** [comment]
Mais a-t-on réussi à lire avec le manuscrit en main ? Pardon, ce n'est pas dans ma partie, donc j'ai complètement perdu ça de vue.
Si on a su lire, on vire en effet la mention unclear et hop :)

**Comment by PrunelleDeleville** [comment]
Je ne me souviens plus si nous voulons garder une trace des autocorrections des mss autres que V?
Ex : 
1. https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/7eb91b79d6996ed543e38096c15a7a48a0730684/TEI/%C2%A71-134_Brodtkorb.xml#L310
2. https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/7eb91b79d6996ed543e38096c15a7a48a0730684/TEI/%C2%A71-134_Brodtkorb.xml#L314

**Comment by PrunelleDeleville** [comment]
Il me semble qu'on a su lire. Tous les trucs de problème de transparence n'en étaient plus sur place.

**Comment by Camille-Carnaille** [comment]
Pour ta question liée aux autocorrections, j'avais noté que non conformément au Google Doc, donc j'espère que c'est vraiment le cas, parce que je n'ai rien indiqué dans ce sens pour ma part, oups !

**Comment by PrunelleDeleville** [comment]
Dans mes souvenirs, c'est aussi ce que nous avions dit, mais j'ai préféré vous poser la question, par acquit de conscience.
