### ISSUE TITLE
Collation - Exponctuation

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#4]
`Question` entremêlée : 
Est-il préférable d'indiquer des cas d'exponctuation qui sont parallèles à des variantes dans _app_ directement ? 
Ou peut-on les indiquer en _del_ hors _app_ ?
Dans ce cas, peut-on s'assurer d'un rendu aussi en apparat ?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/08511187a842c2d808b35a8d34491d5bf11b6017/TEI/Collation.xml#L267

**Comment by gabays** [comment]
L'utilisation de `<del>` me parait correcte.
