### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#42]
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8a87766c7766b09896ae80342d35435562027243/TEI/%C2%A7483-851_Camille.xml#L4188-L4189

**Comment by Camille-Carnaille** [comment]
cf. manuscrit : https://gallica.bnf.fr/ark:/12148/btv1b52513332z/f62.item.r=fran%C3%A7ais%2022550.zoom

**Comment by Camille-Carnaille** [comment]
Tu vois, je suis juste une patate : je n'avais pas compris le sens de la barre au-dessus de "qu", mais du coup je modifie en
qu<add place=above hand=main3>ant</add> avient.
Criez-moi dessus si cela vous semble faux :)

**Comment by PrunelleDeleville** [comment]
c'est peut-être moi qui n'aie pas compris. Et tu n'es pas une patate!!!!

**Comment by SophieLecomte** [comment]
Je suis d'accord avec Prunelle, sur tout (y compris pas patate^^)

**Comment by SophieLecomte** [comment]
(je n'ai pas regardé le ms)
