### ISSUE TITLE
Ponctuation et coquilles - 2

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#43]
1) 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/4fc3b77826ae9d4f491a26e5b2d0d84d49d79b00/TEI/%C2%A7483-851_Camille.xml#L4426-L4427

2) 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/4fc3b77826ae9d4f491a26e5b2d0d84d49d79b00/TEI/%C2%A7483-851_Camille.xml#L4677-L4678

**Comment by PrunelleDeleville** [comment]
1. oui en effet pour "quil" il y a peut-être des cas où on a oublié d'écrire "qu'il" et d'autres pour lesquels on relève l'emploi de "quil" pour "qui" (ce qui arrive parfois quand le mot est suivi d'un autre commençant par "l". 
2. bien sûr, à résoudre en "us" :-) => nous

**Comment by Camille-Carnaille** [comment]
2. Super, merci, c'est résolu !
1. Je ne comprends pas bien le cas où "quil" signifie "qui", mais il y a en effet toute une série d'occurrences où je ne comprendrai pas bien que ce soit "qu'il", je suis un peu perdue du coup

**Comment by PrunelleDeleville** [comment]
3. envoie-moi ces cas, si tu veux

**Comment by SophieLecomte** [comment]
1. en réponse à ta question. C'est une hypercorrection quil = qui (et à l'inverse on a aussi qu'i pour qu'il etc.). Explications et exemples dans Ménard (cf. index, dans les §§ 360 et qqs d'après mes souvenirs), il revient sur toutes les alternances.
