### ISSUE TITLE
Bébé Camille collationne 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#44]
Coucou les filles ! 
Je l'avais annoncée : l'avalanche de questions de Camille prend ses marques en collation est arrivée !

Plusieurs ordres de questions : 
1) Les choses que je n'ai même pas pris la peine d'intégrer, mais sur lesquelles je préfère revenir pour m'en assurer avec vous : 
Géré par Prunelle :) 

2) Les choses sur lesquelles je m'interroge après les avoir quand même intégrées : 
c) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/d09b3a02ad166f027153997372e50ce87f78a601/TEI/%C2%A7483-851_Camille.xml#L691-L692
e) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/d09b3a02ad166f027153997372e50ce87f78a601/TEI/%C2%A7483-851_Camille.xml#L698-L699

3) Les variantes qui me semblent plus simplement mériter d'être intégrées comme corrections de V3, clairement fautif : 
a) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/d09b3a02ad166f027153997372e50ce87f78a601/TEI/%C2%A7483-851_Camille.xml#L674 
b) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/d09b3a02ad166f027153997372e50ce87f78a601/TEI/%C2%A7483-851_Camille.xml#L771
c) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/d09b3a02ad166f027153997372e50ce87f78a601/TEI/%C2%A7483-851_Camille.xml#L801

**Comment by PrunelleDeleville** [comment]
1. tu as eu raison de ne pas relever cela

**Comment by PrunelleDeleville** [comment]
2. a) non ; b) non (d'après moi mais cela intéressait Simone, je les ai gardé en commentaire) c) non (d'après moi) d) non
e) peut-être f)oui  g) oui pour les changements de mode (voir ce qu'en disait Simone) h) oui i) non j) non

**Comment by PrunelleDeleville** [comment]
3. on doit, je pense, parler en équipe de la façon dont on corrige. Pour l'instant, je ne suis pas intervenue sur le texte.

**Comment by Camille-Carnaille** [comment]
Mille mercis Prunelle, pour la mise à jour du fichier de collation en bonus, tu es parfaite <3 
J'ai intégré toutes tes réponses dans mon fichier et modifie mon issue pour ne laisser que les questions laissées avec un doute à l'intention de Sophie. J'ai aussi créé un fichier Word avec mes propres commentaires pour la flexion avoit/ot :)

**Comment by SophieLecomte** [comment]
2c: je pense que oui (tout mot en plus ou en moins, et la présence/absence était intéressante selon Simone, dans mes souvenirs)
2e: oui, toute variante de ce type. Après, si c'est systématique, on peut peut-être en faire le relevé et supprimer cela en phase de révision, tout cela à avoir avec Simone
3: idem avis Prunelle
Sorry pour le style télégraphique. Bisous

**Comment by Camille-Carnaille** [comment]
Les filles, je suis désolée, mais je repose la question des "en" ajoutés/absents. 
Type "Dont n'en [absent dans B et X2] y ot", vous me confirmez qu'on ne garde pas ? Suivant une question que j'avais posée, j'avais compris que non, mais ne le lis pas textuellement dans le document du Drive, alors je préfère m'en assure encore une fois, pardon !
