### ISSUE TITLE
Collation ?

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#46]
Encore des questions de collationne-t-on ou non ?
a) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L804
b) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L836
c) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L989
Cela me semble simplement être une coquille de X2
d) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L1083
Faut-il ajouter la mini-variante (un peu étrange) de X2 ?
e) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L1157
f) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L1167
g) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L1466
Faute évidente de X2
h) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L1523
i) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/8c957b6d7848d28952c03f67a366158b972a3b19/TEI/%C2%A7483-851_Camille.xml#L1557
Faute évidente de X2

**Comment by simoneve74** [comment]
a) à g) oui, mieux inclure les variantes dans la collation, même s'il s'agit parfois de variantes banales.

h) et i) fautes claires, mais attention, pour éviter des ambiguïtés, on n'utilisera faute 'évidente' que lorsqu'il s'agit d'une faute qui nous aide à éclairer les relations entre les mss

**Comment by Camille-Carnaille** [comment]
Nouvelle petite volée de questions : 
1) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/f46d1f575118e5846fcacf77a963c43e129f6909/TEI/%C2%A7483-851_Camille.xml#L2161 
2) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/f46d1f575118e5846fcacf77a963c43e129f6909/TEI/%C2%A7483-851_Camille.xml#L1786-L1787
3) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/f46d1f575118e5846fcacf77a963c43e129f6909/TEI/%C2%A7483-851_Camille.xml#L1699
4) https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/f46d1f575118e5846fcacf77a963c43e129f6909/TEI/%C2%A7483-851_Camille.xml#L1533

**Comment by PrunelleDeleville** [comment]
Personnellement, je garderai la collation de 1, 2, 3 mais pas de 4.

**Comment by SophieLecomte** [comment]
Je réponds de nouveau dans l'ordre: a) "vous pouroffrez" et "pour vous offrez" à garder, le sens change, à moins que quelque chose m'échappe; je n'ai pas cherché mais le verbe "pouroffrir" peut se scinder ainsi?; b) à voir si c'est répétitif et qu'on souhaite le supprimer en s'en justifiant dans l'introduction, mais je garderais; c) si je comprends bien, il y a une histoire de pronom personnel ou de négation: je garderais donc; d) voir ce qu'on choisit de faire (pour avoir un point de comparaison, pour le Guiron, on n'enregistrait les coquilles et co. des mss. collationnés que lorsqu'ils se trouvaient dans une variante qu'on enregistrait pour une autre raison, sinon on laissait tomber; e) je dirais que oui; f) aussi; g) idem réponse pour (d) ; h) je ne suis pas sûre qu'il s'agisse d'une faute évidente, dans les mss. de "Guy" au XVe 'comment' et 'comme' étaient souvent interchangeables: à voir; i) idem réponse (d) et (g)

**Comment by SophieLecomte** [comment]
1) oui
2) oui
3) à voir, pour le Guiron on avait laissé tomber comme un fait de pure 'surface'
4) idem réponse ci-dessus

**Comment by PrunelleDeleville** [comment]
a) collationner toutes les incises de ce type?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L316
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L317

b) lorsqu'on veut rendre compte de l'absence d'une incise (si on veut en rendre compte), faut-il mettre dans le lemme l'incise avec ou sans les virgules
Ex: https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L383

c) variations du singulier au pluriel
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L324
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L325

d) garder une variante "ci" / "çaiens"?

e) variation entre "et" et "puis"
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L420
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L421

f) variation entre "et" et "et puis"
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L772

g) changement dans l'ordre entre sujet et verbe
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L599

h) garder "mieux" / "le mieux"?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L622

i) alternance "tant comme" / "tout comme"
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L689

j) alternance "nul homme" / "nului"?

k) alternance "Ainsi" / "En tele maniere", très fréquente dans B
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L713

l) alternance "contre " / "encontre" (pas nécessaire dans la mesure où nous n'avons pas gardé "vers" / "envers")
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/73a62ebac53bff7b5359816d8ce1e8355f8a998e/TEI/%C2%A7135-188_Prunelle.xml#L853

J'ai conscience que ces points de collation ne sont pas cruciaux mais mieux vaut qu'on soit d'accord et alimenter ainsi la discussion de jeudi ;-)

**Comment by PrunelleDeleville** [comment]
Je continue mes petites questions ici!
m) Nous avions dit ne pas tenir compte des alternances "cil" / "il", cela vaut donc aussi pour "elle" / "celle"?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/3289a1f31c04b8db1735ca82e33c9410503092a7/TEI/%C2%A71-134_Brodtkorb.xml#L414

n) est-ce que vous voulez garder en variantes le type de formes comme "esbaihis" pour "esbahis"? Cela revient dans B, je pensais donc le garder dans l'analyse linguistique plutôt?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/3289a1f31c04b8db1735ca82e33c9410503092a7/TEI/%C2%A71-134_Brodtkorb.xml#L552
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/3289a1f31c04b8db1735ca82e33c9410503092a7/TEI/%C2%A71-134_Brodtkorb.xml#L553
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/3289a1f31c04b8db1735ca82e33c9410503092a7/TEI/%C2%A71-134_Brodtkorb.xml#L776

o) garder ce type de variation?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/3289a1f31c04b8db1735ca82e33c9410503092a7/TEI/%C2%A71-134_Brodtkorb.xml#L758

p) voulez-vous garder l'emploi du futur "sera" dans G quand les autres manuscrits donnent "ert", ou pouvons-nous garder cela pour l'analyse linguistique?

q) veut-on garder l'expression ou la non expression du forclusif dans la négation?
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/3289a1f31c04b8db1735ca82e33c9410503092a7/TEI/%C2%A71-134_Brodtkorb.xml#L894

r) j'ai relevé dans les variantes les changements d'accord du COD avec l'auxilaire "avoir", cela vous convient-il?
ex : les choses qu'il avoit fait / faites

Merci pour votre attention!

**Comment by simoneve74** [comment]
Bonjour et merci de tout ce gran travail!

Comme commentaire général, il vaut mieux d'être conservateurs à présent, quitte à marquer les cas susceptibles d'être enlevés de l'apparat après (par un signe conventionnel facile à repérer par la suite) - puisqu'elles n'ajoutent rien d'important à nos connaissances sur la relation entre les témoins. 
Tout en sachant que collationner est sacre boulot, nous avons une tradition relativement restreinte: en général, dans ce cas de figure, les philologues ont tendance à conserver les données: apparat positif.
Finalement, il y a un critère impondérable et subjectif mais crucial: le bon sens: une leçon peut être banale jusqu'à ce qu'elle ne le plus: eyes wide open!

Réponses question par question:

a) Incise: oui, collationner les incises - De combien d'occurrences parle-t-on?
b) Sans virgules
c) Garder dans la collation - Mais encore: cas fréquent?
d-f) Pas garder dans la collation, sauf si l'on trouve des cas significatifs (je sais, c'est subjectif, mais je crains qu'à l'heure actuelle pour ces cas il est impossible d'en dire plus)
g-j) Tout garder dans la collation
k) Cette alternance peut ne pas être significative, surtout s'il s'avère que B se comporte systématiquement de la même manière: comme nous ne le savons pas encore à coup sur peut-être, je garderais l'alternance pour le moment: serait-il possible établir un seuil de représentativité? I.e. un seuil au-delà duquel on peut établir avec une probabilité suffisante que B a toujours En tele maniere au lieu de Ansi. Je pose la question.
l) Pas la peine de garder cette alternance.
m) Pas garder
n) Ce sont en effet des données qui relèvent mieux de l'analyse des graphies. Cependant il faudrait noter ces cas.
g) Oui, garder cette alternance - du moins pour le moment
p) Oui, donnée pour une note dans l'analyse de la langue
q-r) Ce sont de choses dont nous allons parler dans la partie d'examen de la langue. Il faut en prendre note. Je me demande alors si ce n'est pas plus économique à ce stade de garder ces données dans l'apparat pour le moment.

**Comment by Camille-Carnaille** [comment]
Réunion du 22/09/22 : 

Réponses à Camille : 
1) Changement de sens > oui
2) Absence de lettrine en début de § > oui :  <note type apparat>Pas de lettrine G</note>
3) ore-orendroit > non quand systématique 
De même que toutes variations d'adverbes (meismement/meismes)
4) idem non 

Réponses à Prunelle : 
a) Oui, par souci d'analyse discursive et compréhension des passages plus complexes
b) Ponctuation OK
c) Singulier/pluriel : Non dans G (fluctuation à rapprocher CS/CR) et sauf en cas de changement de sens 
d) NON 
e) NON
f) NON
g) OUI 
h) OUI 
i) NON, sauf en cas de changement de sens 
j) OUI (nul homme-nului / homs-on / etc.)
k) NON car systématique ou presque 
l) NON pour changement de préfixe, mais si changement de lemme on garde 
m) NON
n) NON (mais o-oi pour analyse linguistique, de même dans le cas de deuil) 
o) NON 
p) NON si systématique pour G (préciser ce cas particulier dans les fluctuations de temps verbal) 
q) NON (pas présence/absence forclusif, alternance mie/pas, sauf si significatif, mais en garder qqs exemples pour les indiquer en analyse linguistique) 
r) OUI
=> Décisions à inclure dans le Google Doc !

**Comment by SophieLecomte** [comment]
Bon retour sur GitHub! Pour le 1, j'enregistrerais (parce que ça ne me paraît pas récurrent); en revanche 2. c'est précisément l'exemple que j'ai oublié dans la note au texte et qui revient mille fois: "jusques atant que" / "dessi adonc que" dans B. C'est tellement répétitif que j'aurais tendance à le supprimer en le mentionnant dans l'introduction, comme on le fait d'ailleurs pour d'autres variantes. C'est à Simone de trancher.

**Comment by simoneve74** [comment]
OK

**Comment by PrunelleDeleville** [comment]
OK aussi!

**Comment by simoneve74** [comment]
Tout va bien ici? Peut-on clôturer, non?
