### ISSUE TITLE
Difficulté lecture variantes mss

### ISSUE THREAD

**Issue by PrunelleDeleville** [CycleDes7Sages/CycleDes7Sages.github.io#47]

**Comment by PrunelleDeleville** [comment]
Coucou les filles,
je ne suis pas sûre de réussir à lire une partie du texte de B à la fin de ce morceau (page 700 du pdf, colonne b) : 
![image](https://user-images.githubusercontent.com/100917533/184893837-b52c939d-28ae-4155-9efa-98e7e2f4bef2.png)
ce qui correspond à cette ligne-là (après "vie que" ??) : https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/30ed36099e7ca2c70255dcbfe6a028e9d9f364da/TEI/%C2%A71-134_Brodtkorb.xml#L623

**Comment by PrunelleDeleville** [comment]
idem sur B : on lit à la fin de la ligne "quis"?
![image](https://user-images.githubusercontent.com/100917533/184894274-6b5403de-b9d3-449c-939f-62215ff2284c.png)

**Comment by Camille-Carnaille** [comment]
Coucou,
Pour le premier cas, j'aurais tendance à lire nul, mais cela n'est pas très (du tout) fondé comme lecture. Je sèche un peu, mais y réfléchis. 
Pour le deuxième cas, je dirais quis sans trop d'hésitation, pour avoir croisé le mot ainsi présenté à d'autres reprises sauf erreur.

**Comment by PrunelleDeleville** [comment]
Merci! Alors je valide "quis" et j'attends Sophie (mais ce n'est pas urgent) pour "nuls"

**Comment by PrunelleDeleville** [comment]
recoucou!
Dans ce passage où tous les autres manuscrits offrent "soigneus", je lis cette forme dans G: est-ce "soigneus" ou "seigneurs", "soigneurs"? (il a eu un peu de mal sur le mot)
![image](https://user-images.githubusercontent.com/100917533/185415451-a1de46b6-4525-42fa-9a1f-d91c48ca3f60.png)

**Comment by PrunelleDeleville** [comment]
Coucou, dans G, au f. 353r, au début du paragraphe suivant la lettrine "L", je lis ceci:
![image](https://user-images.githubusercontent.com/100917533/186702180-cc449eb5-6963-4de0-b444-5614a4efa988.png)

On dirait presque un petit cœur, alors que manque justement que le mot "cuer" qui devrait se trouver ici. Quelqu'un a déjà vu ce truc?

**Comment by Camille-Carnaille** [comment]
Oooh un emoji du 15e siècle ! 
Jamais vu, mais il y a peu de doutes sur ce coup, si ?

**Comment by PrunelleDeleville** [comment]
Merci, Camille.
et là, on lit bien un "l" avant "oy"? Je vous pose la question, car on dirait que ce "l" est ajouté, alors que c'est une erreur dans la syntaxe de la phrase:
![image](https://user-images.githubusercontent.com/100917533/186915040-c1c2041d-ed96-43fa-bab3-9f13c846426a.png)

**Comment by SophieLecomte** [comment]
Coucou les filles. Je réponds dans l'ordre:

**Comment by Camille-Carnaille** [comment]
Je me permets de clore cette issue :)
