### ISSUE TITLE
Collation - Apparat à multi-étages 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#5]
Bonne ou mauvaise idée, au niveau de la pure TEI, de mêler des variantes plus larges et des variantes plus ténues, ou est-il préférable de coder tout comme des variantes plus larges ?
Les _rdgGrp_ seraient une solution vraiment pratique dans ce cas ?

https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/08511187a842c2d808b35a8d34491d5bf11b6017/TEI/Collation.xml#L269

**Comment by gabays** [comment]
C'est bien comme ça
