### ISSUE TITLE
Supplied > variante différente de G

### ISSUE THREAD

**Issue by PrunelleDeleville** [CycleDes7Sages/CycleDes7Sages.github.io#50]
Coucou,
je me demande comment baliser les deux cas suivants où Brodtkorb corrige selon BX2 en ajoutant un bout manquant mais où G adopte une autre stratégie de correction.
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/ac99d599f4ead80854499b3253e74299124f3f3c/TEI/%C2%A71-134_Brodtkorb.xml#L10253
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/ac99d599f4ead80854499b3253e74299124f3f3c/TEI/%C2%A71-134_Brodtkorb.xml#L10254
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/ac99d599f4ead80854499b3253e74299124f3f3c/TEI/%C2%A71-134_Brodtkorb.xml#L10255

**Comment by SophieLecomte** [comment]
Je dirais que, si on se dit qu'on corrige toujours en suivant B, on devrait effectivement intervenir d'après BX2, en mettant que c'est omis dans V2 et en mettant la variante de G. Ai-je bien compris la question?
