### ISSUE TITLE
@Resp Supplied

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#51]
Chère équipe !
à l'ordre des questions techniques dans la révision de l'ODD qui s'annonce pour la mise en forme de notre édition et pour la partie numérique de l'introduction, je me demandais si nous souhaitions conserver la mention de la responsabilité de la correction 
(<supplied @resp="CC/PD/SL/Brodtkorb">) que nous avions intégrée pour indiquer que la correction était celle de Brodtkorb et non celle que nous voulions nous-mêmes présenter. Maintenant que la collation a été entièrement prise en charge par nos soins, est-ce toujours nécessaire selon vous ?
Très belle semaine et à bien vite !

**Comment by simoneve74** [comment]
Je pense en effet qu'il n'est plus nécessaire de garder @resp. Intéressant sans doute de s'en souvenir pour l'avenir et l'"historique" de nos pratiques d'encodage.

**Comment by PrunelleDeleville** [comment]
Idem! Du coup, je peux l'enlever dans le fichier §1-134?

**Comment by simoneve74** [comment]
@PrunelleDeleville oui, enlève
