### ISSUE TITLE
Question subsistante 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#52]
Bonjour à tous !
Je clôture pour de vrai de vrai cette fois ma collation et parcours mes commentaires, l'occasion de trouver cette petite question liée à la lecture de B et X2 surtout : 
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/c1e85a5fc01c4e383ffeb635ca0c57b62a718c99/TEI/%C2%A7483-851_Camille.xml#L4085
à toute fin utile, ce paragraphe se trouve f. 449vb dans B, f. 104vb dans X2 et 458rb dans G. 
Mille mercis une fois de plus !

**Comment by PrunelleDeleville** [comment]
Coucou!
Je copie-colle le morceau car j'ai eu du mal à le trouver (mais je ne sais pas si la capture d'écran va fonctionner), alors je me dis que ça peut aider.
Je lis "s'auna" du verbe "auner" ="rassembler"
![image](https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/assets/100917533/c2470666-bb62-4657-a295-b5deb77ab2b4)

**Comment by SophieLecomte** [comment]
Je n'ai pas de solution dans ce cas: on attend un futur, et le "v" en milieu de mot me semble inhabituel dans les pratiques du copistes. Je transcrirais "savna (sic)" dans l'apparat.

**Comment by simoneve74** [comment]
Il y a évidemment un problème soit du copiste (source fautive? mauvaise lecture?) soit notre (un problème que nous ne savons pas reconnaitre). Possible qu'une analyse ultérieure puisse nous amener à une hypothèse de reconstruction (via diffraction...). 

En tout cas, je mettrais dans l'apparat: savna (sic) ou tout simplement savna

**Comment by Camille-Carnaille** [comment]
Mille mercis pour vos réponses !
Le cas de X2 me paraît aussi intéressant, je vous le partage donc, peut-être surtout pour l'étude du stemma : 
![image](https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/assets/79918282/3d4a9c39-bb6a-4bbe-bf07-8c50c52d41e0)
On a donc bien "sara", comme à mi-chemin entre "sera" et "savna" donc. Je balise le tout tel que je l'avais indiqué donc ?

**Comment by PrunelleDeleville** [comment]
Oui, je baliserais comme tu l'as indiqué.
