### ISSUE TITLE
Rendu des <note type="apparat"> et balisage

### ISSUE THREAD

**Issue by SophieLecomte** [CycleDes7Sages/CycleDes7Sages.github.io#54]
(Pour s'en souvenir) il faudrait que :
- les balises "<note type="apparat"> qui concernent la division en § des autres mss. soient rendues par des notes dans la marge, comme décidé hier;
- le reste des notes apparaisse en troisième couche d'apparat, si autorisé par la SATF.
Ma question est donc la suivante: balise-t-on pour l'instant de la même façon des notes qui apparaîtront à des endroits différents de la page imprimée?

**Comment by PrunelleDeleville** [comment]
Il me semble que nous avons balisé de deux façons : note type apparat / note type note critique. Et donc j'imagine qu'on pourra demander au fichier de séparer ces notes puisqu'elles sont de deux types différents.

**Comment by Camille-Carnaille** [comment]
Je comprends la question comme Prunelle, mais peut-être y a-t-il d'autres choses que ta question envisage, Sophie ?
Il ne me semble pas y avoir des informations de mise en page du manuscrit de base et de mise en page des autres manuscrits qui soient concordantes : comme le rappelle Prunelle, la section "note" me semble reprendre le tout, que l'on pourra sans souci distinguer puisque chaque section est précisée. Mais, une fois encore, s'il y a autre chose, je suis tout ouïe !

**Comment by SophieLecomte** [comment]
J'avais oublié, au moment de poser ma question, que le "type" distinguait les 2 types. My mistake!
