### ISSUE TITLE
Collation - Nouveau paragraphe 

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#6]
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/08511187a842c2d808b35a8d34491d5bf11b6017/TEI/Collation.xml#L285

Y a-t-il une manière toute prête pour comment indiquer qu'un nouveau paragraphe dans le document de base n'est pas indiqué comme un nouveau dans un autre témoin ?

**Comment by gabays** [comment]
Tu peux mettre_
```xml
<p xml:id="P483"><app from="xml:id="P483"><rdg wit="#B"/></app>
