### ISSUE TITLE
`@n` or `@xml:id`

### ISSUE THREAD

**Issue by gabays** [CycleDes7Sages/CycleDes7Sages.github.io#7]
Je recommande d'utiliser `@xml:id` plutôt que `@n` car si, par hasard, tu as fait une erreur et que tu as répété deux fois le même chiffre, Oxygen va te mettre un avertissement.

Attention, il n'est pas possible de commencer un `@xml:id` par un chiffre, il faut donc ajouter une lettre (par exp. _p_ comme _paragraphe_) devant le chiffre, du type `@xml:id="P484"`

https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/08511187a842c2d808b35a8d34491d5bf11b6017/TEI/Collation.xml#L325

**Comment by Camille-Carnaille** [comment]
Je crée ici la note, pour qu'on crée un jour le schematron (mais après les essais infructueux d'aujourd'hui), je tremble un peu en le disant pour ces paragraphes

**Comment by Camille-Carnaille** [comment]
Problème résolu pour les paragraphes dans le header :)
