### ISSUE TITLE
ODD - Said direct

### ISSUE THREAD

**Issue by Camille-Carnaille** [CycleDes7Sages/CycleDes7Sages.github.io#8]
Petit relevé des soucis qui continuent à se poser : 

Notre fameux said @direct à parvenir à combattre :
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/e4243ee89a50244730db9106f77ffbe13a873c08/TEI/Pelyarmenus.odd#L541 

La question des decoNote, en parallèle de celle des handNote, qu'on n'a finalement pas réglée pour ce qui relève du xml:id dans la deuxième occurrence liée à V3 (après la présentation de V2)
La solution scritpRef qu'on a employée pour les handNote ne semble pas possible dans ce cas de figure
https://github.com/CycleDes7Sages/CycleDes7Sages.github.io/blob/e4243ee89a50244730db9106f77ffbe13a873c08/TEI/Pelyarmenus.odd#L275

**Comment by Camille-Carnaille** [comment]
Problème 2 résolu 
Problème 1 reste ouvert :)

**Comment by PrunelleDeleville** [comment]
coucou
